### PR TITLE
 Add instruction on how to "take control" of the dashboard

### PR DESCRIPTION
**Pull request by torvitas**
Add instructions on how to prepare the dashboard before enabling the card

### CODE REVIEW

**Comment by torvitas** [comment]
I see that there is constant change to the UI so I would totally understand if you ditch this PR.

**Comment by Hypfer** [comment]
> I see that there is constant change to the UI so I would totally understand if you ditch this PR.

Yep, this.
Are the current instructions wrong or just not detailed enough?

**Comment by torvitas** [comment]
The current instruction mention that you need to enable "storage mode" which does not exist anymore instead the steps I added are necessary to make the map entity work.

**Comment by torvitas** [comment]
Also without these details I was struggling for about an hour and was causing a lot of noise in the valetudo telegram channel so I thought it would reduce the support burden if that information were in the docs.

**Pull request merged**
